version: "3.6"

services:
  dog_vs_cat_flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python app.py
    restart: always
    volumes:
      - .:/app/
    ports:
      - "5001:5001"
    
